# Generated by Django 4.0.5 on 2023-01-18 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=255)),
                ('Patient_Phone', models.CharField(max_length=12)),
                ('Chair_Number', models.CharField(max_length=50)),
                ('Treatment_Category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.CharField(max_length=10)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.patientdetails')),
            ],
        ),
    ]
